// src/app/about/page.tsx
import Link from 'next/link';
import { cn } from '@/lib/utils';
import {
  PERSONAL,
  JOB_COMPANY,
  JOB_POSITION,
  CHANNELS,
  CREDLY_URL,
} from '@/constants';
import { FlipWords } from '@/components/ui/flip-words';
import { AnimatedTestimonials } from '@/components/ui/animated-testimonials';

export const metadata = {
  title: 'About',
};

const Highlight = ({
  children,
  className,
}: {
  children: React.ReactNode;
  className?: string;
}) => {
  return (
    <span
      className={cn(
        'text-primary bg-emerald-100 px-1 py-0.5 font-bold dark:bg-yellow-700/[0.2]',
        className,
      )}
    >
      {children}
    </span>
  );
};

const page = () => {
  const flipWords = ['Meee', 'Iii', 'Myselfff'];

  return (
    <div className="container mx-auto px-2 py-4 lg:py-8">
      <div className="mx-auto max-w-[58rem] px-4">
        <h1 className="mt-2 text-4xl font-bold tracking-tight">
          <FlipWords className="px-0" words={flipWords} />
          😎
        </h1>

        <p className="mt-6 leading-7 first:mt-0">
          Hi, I&apos;m Kar Chun! I&apos;m an{' '}
          <span className="text-primary">{JOB_POSITION}</span> at{' '}
          <span className="text-intel">{JOB_COMPANY}</span>. Welcome to my
          website, visit my{' '}
          <Link
            className="text-primary decoration-from-font [text-underline-position:from-font] hover:underline"
            href="/blog"
          >
            blog
          </Link>
          &nbsp;for documentation, tutorials, and more. I love to code and
          design software architecture.
        </p>

        <p className="mt-6 leading-7 first:mt-0">
          My ambition is to develop a new technology that can revolutionize the
          world. As part of my motivation to inspire people, this site shares
          what I have learned and studied previously. It would be the greatest
          thing I could ever hope for if someone looked at me and said,{' '}
          <Highlight>Thanks to you, I didn&apos;t give up</Highlight>🥳.
        </p>

        <p className="mt-6 leading-7 first:mt-0">
          You can contact me via these channels!
        </p>

        <ul className="mt-2 flex list-disc flex-col gap-2 pl-9">
          {Object.entries(CHANNELS).map(([key, { title, href }]) => (
            <li key={key}>
              <Link
                href={href}
                className="text-primary decoration-from-font [text-underline-position:from-font] hover:underline"
              >
                {title}
              </Link>
            </li>
          ))}
        </ul>

        <p className="mt-6 leading-7 first:mt-0">
          Here is my{' '}
          <Link
            className="text-primary decoration-from-font [text-underline-position:from-font] hover:underline"
            href={CREDLY_URL}
          >
            Credly
          </Link>{' '}
          profile, where you can find my certifications and badges. <br />
          You can refer to my{' '}
          <Link
            className="text-primary decoration-from-font [text-underline-position:from-font] hover:underline"
            href="/hub/journey"
          >
            journey
          </Link>{' '}
          in the timelime. <br />
          It is my hope that you can find something useful or helpful here.
          Thank you!
        </p>

        <AnimatedTestimonials testimonials={PERSONAL} />
      </div>
    </div>
  );
};

export default page;

// src/.vitepress/theme/components/About.vue
<script setup lang="ts">
import MarkdownIt from "markdown-it";

const markdown = new MarkdownIt();

const myQuote = "`Thanks to you, I didn't give up`";
const aboutMarkDown = `
Hi, I'm Kar Chun! I'm an Infrastructure and DevOps Engineer at Intel.
Welcome to my website, visit my [blog](./blog) for documentation, tutorials, and more.
I love to code and design software architecture.

My ambition is to develop a new technology that can revolutionize the world.
As part of my motivation to inspire people, this site shares what I have learned and studied previously.
If someone looked at me and said ${myQuote} that would be the best thing I could ever hope for. 🥳

You can contact me via these channels!

- [GitHub](https://github.com/karchunt)
- [Linkedin](https://www.linkedin.com/in/karchuntan)
- [Newsletter](https://karchunt.substack.com)
- [karchuntan.1999@gmail.com](mailto:karchuntan.1999@gmail.com)

It is my hope that you can find something useful or helpful here. Thank you!
`;
</script>

<template>
  <div class="about">
    <div className="flex flex-col justify-between gap-4 md:flex-row">
      <div className="flex flex-1 flex-col gap-4">
        <h1>Meee 😎</h1>
        <div v-html="markdown.render(aboutMarkDown)"></div>
      </div>

      <div className="relative flex">
        <img src="/anotherme.webp" alt="karchunt" class="rounded-xl" />
      </div>
    </div>
  </div>
</template>

<style></style>
